kind: PersistentVolume
apiVersion: v1
metadata:
  name: charm-storage-path
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: microk8s-hostpath
  hostPath:
    path: "/mnt/data/vol1"
      