kind: PersistentVolume
apiVersion: v1
metadata:
  name: charm-storage-unit
spec:
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: portainer-juju-unit-storage
  hostPath:
    path: "/mnt/data/vol1"
      